### ISSUE TITLE
多号码保号任务失败

### ISSUE THREAD

**Issue by GV13057911485** [Issac-v/textnowProtect#1]
当进行多号码（我测试了36个）的时候，任务可以执行，也不报错，但我的目标号码上没有收到消息。

**Comment by Issac-v** [comment]
确认按照[教程](https://github.com/Arronlong/py_scripts/tree/master/scripts/textnow)的格式输入么? 
本库只是去除其他功能, 精简了代码的二创. 建议尝试[原作者脚本](https://github.com/Arronlong/py_scripts), 如果仍有问题可以向他反馈.

**Comment by GV13057911485** [comment]
感谢您的回复。
测试给36个号码保号，看起来任务是成功的，但接收方却没有收到消息，而且登陆上textnow之后也没有看到发送了消息。


Your Positive Review is Our Best Motivation!

Best Regards
Teresa | Sales Department
*Email: sales.growant@gmail.com <sales.growant@gmail.com>*
*Web-Shop: www.growant.com <http://www.growant.com/> (US free shipping)*

*Amazon Shop:  Amazon US <http://www.amazon.com/shops/growant>  (Prime free
shipping)*
*Facebook Page: www.facebook.com/growant <http://www.facebook.com/growant>
(Coupons available)*

**Comment by Issac-v** [comment]
已由上游解决

**Comment by whtiehack** [comment]
感谢  @Issac-v
